# Generated by Django 5.1.7 on 2025-04-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pizza_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='user',
        ),
    ]
